version: '3'
services:
    redis:
        image: redis
        container_name: tcp_server_redis
        ports:
            - 7379:6379
        healthcheck:
            test: ['CMD', 'redis-cli', 'ping']
            interval: 4s
            timeout: 5s
            retries: 5

    tcp_server:
        depends_on:
            redis:
                condition: service_healthy
        build:
            context: .
            dockerfile: resources/docker/goLang/Dockerfile
        container_name: tcp_server_golang
        volumes:
            - .:/go/src/tcp_server
        working_dir: /go/src/tcp_server
        ports:
            - 4000:4000
        environment:
            TCP_HOST: localhost
            TCP_PORT: 4000
            REDIS_HOST: redis
            REDIS_PORT: 6379
